package Vista;

import Controlador.Brain;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac
 */
public class Principal extends javax.swing.JFrame {

    int Identificador = 3;
    String generador;
    String nombreTxt;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
       JOptionPane.showMessageDialog(null, "Tienen que crear una carpeta llamada 'ArchivoTxt' en su disco C de su computador, luego, dentro de ella, creen el archivo que quieren decodificar - Aviso temporal para nosotros");
       JOptionPane.showMessageDialog(null, "El programa les va a crear un archivo .crc con el nombre que le dieron al archivo de codificacion. Dentro de él, está el generador en la primera linea, y los codeword que se crearon en las demas lineas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BAbrir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BAbrir.setText("Codificar");
        BAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAbrirActionPerformed(evt);
            }
        });

        jButton1.setText("Decodificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BAbrir)
                    .addComponent(jButton1))
                .addGap(0, 312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAbrirActionPerformed
        generador = JOptionPane.showInputDialog("Ingrese el polinomio generador"); //Recibe el generador
        if (generador != null) { //  Verifica si el usuario no presionó cancelar
            Brain.AsignarPolinomioGenerador(generador); // Se asigna el generador al codigo principal
            int opcion = JOptionPane.showConfirmDialog(null, "A continuacion, ingresa la ruta del archivo a codificar", "Aviso", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == 0) { // Verifica si el usuario desea continuar, o le dio en cancelar al escoger la ruta del archivo
                JFileChooser chooser = new JFileChooser(); // Escoge el archivo
                int conf = chooser.showOpenDialog(null);
                if (conf == JFileChooser.APPROVE_OPTION) { // Más verificacion por si el usuario desea cancelar el proceso
                    File f = chooser.getSelectedFile();
                    nombreTxt = f.getName();
                    Brain.AsignarNombreSalida(nombreTxt); // Le asigna el nombre que el usuario dio
                    Identificador = 1;
                    Brain.GetInfo(f, Identificador);
                }
            }
        }
    }//GEN-LAST:event_BAbrirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        generador = JOptionPane.showInputDialog("Ingrese el polinomio generador"); //Recibe el generador
        if (generador != null) { //  Verifica si el usuario no presionó cancelar
            Brain.AsignarPolinomioGenerador(generador); // Se asigna el generador al codigo principal
            int opcion = JOptionPane.showConfirmDialog(null, "A continuacion, ingresa la ruta del archivo a codificar", "Aviso", JOptionPane.OK_CANCEL_OPTION);
            if (opcion == 0) { // Verifica si el usuario desea continuar, o le dio en cancelar al escoger la ruta del archivo
                JFileChooser chooser = new JFileChooser(); // Escoge el archivo
                int conf = chooser.showOpenDialog(null);
                if (conf == JFileChooser.APPROVE_OPTION) { // Más verificacion por si el usuario desea cancelar el proceso
                    int res = JOptionPane.showConfirmDialog(null, "¿Desea colocarle un nombre especifico a su archivo de salida?");
                    if (res == 0) { // Verifica la respuesta si el usuario desea un nombre o no
                        nombreTxt = JOptionPane.showInputDialog(null, "Ingrese el nombre de tu archivo de salida");
                        Brain.AsignarNombreSalida(nombreTxt); // Le asigna el nombre que el usuario dio
                        File f = chooser.getSelectedFile();
                        Identificador = 2;
                        Brain.GetInfo(f, Identificador);
                    } else if (res == 1) {
                        nombreTxt = "Salida"; // Le coloca por defecto "Salida" al archivo, en caso que el usuario diga que no desea colocarle 
                        JOptionPane.showMessageDialog(null, "Se ha colocado por defecto el nombre 'Salida' a su archivo y se ha generado exitosamente");
                        Brain.AsignarNombreSalida(nombreTxt);
                        File f = chooser.getSelectedFile();
                        Identificador = 1;
                        Brain.GetInfo(f, Identificador);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAbrir;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
