package Vista;

import Controlador.Brain;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Isaac
 */
public class Principal extends javax.swing.JFrame {

    int Identificador = 3;
    String generador;
    String nombreFile;
    File f;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        initPn.setVisible(true);
        DeteccionPn.setVisible(false);
        CorreccionPn.setVisible(false);
        MenuPn.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        HeadPn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BackgroundPn = new javax.swing.JPanel();
        initPn = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        continueBt = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pathTx = new javax.swing.JLabel();
        selectFileBtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        MenuPn = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        correccionRb = new javax.swing.JRadioButton();
        deteccionRb = new javax.swing.JRadioButton();
        DeteccionPn = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        recepcionDetPn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        recibirDetBt = new javax.swing.JLabel();
        selectFileDetBt = new javax.swing.JLabel();
        envioDetPn = new javax.swing.JPanel();
        generadorTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        enviarDetBt = new javax.swing.JLabel();
        CorreccionPn = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        recepcionCorPn = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        recibirCorBt = new javax.swing.JLabel();
        selectFileCorBt = new javax.swing.JLabel();
        envioCorPn = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        enviarCorBt = new javax.swing.JLabel();
        pathCorTx = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(557, 360));
        setMinimumSize(new java.awt.Dimension(557, 360));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(557, 360));
        setResizable(false);
        setSize(new java.awt.Dimension(557, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeadPn.setBackground(new java.awt.Color(58, 112, 147));
        HeadPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTROL DE ERRORES");
        HeadPn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 270, 28));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_24px_1.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        HeadPn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 20));

        getContentPane().add(HeadPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        BackgroundPn.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        initPn.setBackground(new java.awt.Color(255, 255, 255));
        initPn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        initPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(58, 112, 147));
        jLabel13.setText("Seleccione el archivo de entrada:");
        initPn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 250, -1));

        continueBt.setBackground(new java.awt.Color(58, 112, 147));
        continueBt.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        continueBt.setForeground(new java.awt.Color(255, 255, 255));
        continueBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        continueBt.setText("Continuar");
        continueBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(69, 133, 175), 2));
        continueBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        continueBt.setOpaque(true);
        continueBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continueBtMouseClicked(evt);
            }
        });
        initPn.add(continueBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 120, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(58, 112, 147));
        jLabel15.setText("Ruta: ");
        initPn.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        pathTx.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        pathTx.setForeground(new java.awt.Color(58, 112, 147));
        pathTx.setText("\"\"");
        initPn.add(pathTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 370, -1));

        selectFileBtn.setBackground(new java.awt.Color(58, 112, 147));
        selectFileBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        selectFileBtn.setForeground(new java.awt.Color(255, 255, 255));
        selectFileBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectFileBtn.setText("Seleccionar");
        selectFileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectFileBtn.setOpaque(true);
        selectFileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectFileBtnMouseClicked(evt);
            }
        });
        initPn.add(selectFileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 150, 20));

        jPanel2.setBackground(new java.awt.Color(58, 112, 147));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Configuraciones iniciales");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 250, 30));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Settings_24px.png"))); // NOI18N
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        initPn.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 30));

        BackgroundPn.add(initPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 450, 180));

        MenuPn.setBackground(new java.awt.Color(255, 255, 255));
        MenuPn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MenuPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 112, 147));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENÚ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Menu_24px.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        MenuPn.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        correccionRb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(correccionRb);
        correccionRb.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        correccionRb.setForeground(new java.awt.Color(58, 112, 147));
        correccionRb.setText("Corrección");
        correccionRb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correccionRbFocusGained(evt);
            }
        });
        MenuPn.add(correccionRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        deteccionRb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(deteccionRb);
        deteccionRb.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        deteccionRb.setForeground(new java.awt.Color(58, 112, 147));
        deteccionRb.setText("Detección");
        deteccionRb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deteccionRbFocusGained(evt);
            }
        });
        MenuPn.add(deteccionRb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        BackgroundPn.add(MenuPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 190));

        DeteccionPn.setBackground(new java.awt.Color(255, 255, 255));
        DeteccionPn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DeteccionPn.setMaximumSize(new java.awt.Dimension(362, 284));
        DeteccionPn.setMinimumSize(new java.awt.Dimension(362, 284));
        DeteccionPn.setPreferredSize(new java.awt.Dimension(362, 284));
        DeteccionPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(58, 112, 147));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DETECCIÓN");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Detective_24px.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        DeteccionPn.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 30));

        recepcionDetPn.setBackground(new java.awt.Color(255, 255, 255));
        recepcionDetPn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recepción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(58, 112, 147))); // NOI18N
        recepcionDetPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(58, 112, 147));
        jLabel6.setText("Seleccionar archivo: ");
        recepcionDetPn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        recibirDetBt.setBackground(new java.awt.Color(58, 112, 147));
        recibirDetBt.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        recibirDetBt.setForeground(new java.awt.Color(255, 255, 255));
        recibirDetBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recibirDetBt.setText("Recibir");
        recibirDetBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recibirDetBt.setOpaque(true);
        recibirDetBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recibirDetBtMouseClicked(evt);
            }
        });
        recepcionDetPn.add(recibirDetBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        selectFileDetBt.setBackground(new java.awt.Color(58, 112, 147));
        selectFileDetBt.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        selectFileDetBt.setForeground(new java.awt.Color(255, 255, 255));
        selectFileDetBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectFileDetBt.setText("Seleccionar");
        selectFileDetBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectFileDetBt.setOpaque(true);
        selectFileDetBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectFileDetBtMouseClicked(evt);
            }
        });
        recepcionDetPn.add(selectFileDetBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, -1));

        DeteccionPn.add(recepcionDetPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 340, 100));

        envioDetPn.setBackground(new java.awt.Color(255, 255, 255));
        envioDetPn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(58, 112, 147))); // NOI18N
        envioDetPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generadorTf.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        generadorTf.setToolTipText("Polinomio generador");
        generadorTf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        envioDetPn.add(generadorTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 220, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(58, 112, 147));
        jLabel8.setText("Generador:");
        envioDetPn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        enviarDetBt.setBackground(new java.awt.Color(58, 112, 147));
        enviarDetBt.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        enviarDetBt.setForeground(new java.awt.Color(255, 255, 255));
        enviarDetBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enviarDetBt.setText("Enviar");
        enviarDetBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviarDetBt.setOpaque(true);
        enviarDetBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarDetBtMouseClicked(evt);
            }
        });
        envioDetPn.add(enviarDetBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        DeteccionPn.add(envioDetPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 340, 100));

        BackgroundPn.add(DeteccionPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        CorreccionPn.setBackground(new java.awt.Color(255, 255, 255));
        CorreccionPn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CorreccionPn.setMaximumSize(new java.awt.Dimension(362, 284));
        CorreccionPn.setMinimumSize(new java.awt.Dimension(362, 284));
        CorreccionPn.setPreferredSize(new java.awt.Dimension(362, 284));
        CorreccionPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(58, 112, 147));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CORRECCIÓN");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 30));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Erase_24px_1.png"))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        CorreccionPn.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 30));

        recepcionCorPn.setBackground(new java.awt.Color(255, 255, 255));
        recepcionCorPn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recepción", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(58, 112, 147))); // NOI18N
        recepcionCorPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(58, 112, 147));
        jLabel16.setText("Seleccionar archivo: ");
        recepcionCorPn.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        recibirCorBt.setBackground(new java.awt.Color(58, 112, 147));
        recibirCorBt.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        recibirCorBt.setForeground(new java.awt.Color(255, 255, 255));
        recibirCorBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recibirCorBt.setText("Recibir");
        recibirCorBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recibirCorBt.setOpaque(true);
        recibirCorBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recibirCorBtMouseClicked(evt);
            }
        });
        recepcionCorPn.add(recibirCorBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        selectFileCorBt.setBackground(new java.awt.Color(58, 112, 147));
        selectFileCorBt.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        selectFileCorBt.setForeground(new java.awt.Color(255, 255, 255));
        selectFileCorBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectFileCorBt.setText("Seleccionar");
        selectFileCorBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        selectFileCorBt.setOpaque(true);
        selectFileCorBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectFileCorBtMouseClicked(evt);
            }
        });
        recepcionCorPn.add(selectFileCorBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, -1));

        CorreccionPn.add(recepcionCorPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 340, 100));

        envioCorPn.setBackground(new java.awt.Color(255, 255, 255));
        envioCorPn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Envio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(58, 112, 147))); // NOI18N
        envioCorPn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(58, 112, 147));
        jLabel17.setText("Ruta:");
        envioCorPn.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        enviarCorBt.setBackground(new java.awt.Color(58, 112, 147));
        enviarCorBt.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        enviarCorBt.setForeground(new java.awt.Color(255, 255, 255));
        enviarCorBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enviarCorBt.setText("Enviar");
        enviarCorBt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviarCorBt.setOpaque(true);
        enviarCorBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarCorBtMouseClicked(evt);
            }
        });
        envioCorPn.add(enviarCorBt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, -1));

        pathCorTx.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        pathCorTx.setForeground(new java.awt.Color(58, 112, 147));
        pathCorTx.setText("jLabel18");
        envioCorPn.add(pathCorTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 260, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(58, 112, 147));
        jLabel19.setText("Ruta del archivo cargado en memoria");
        envioCorPn.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jLabel19.getAccessibleContext().setAccessibleName("");

        CorreccionPn.add(envioCorPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 340, 100));

        BackgroundPn.add(CorreccionPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        getContentPane().add(BackgroundPn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 560, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        int res = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void selectFileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFileBtnMouseClicked
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            f = chooser.getSelectedFile();
            nombreFile = f.getName();
            Brain.AsignarNombreSalida(nombreFile);
            pathTx.setText(f.getPath());
            pathCorTx.setText(f.getPath());
        }catch(NullPointerException n){ //en caso de no haber seleccionado archivo
            JOptionPane.showMessageDialog(null, "No se ha especificado la ruta del archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_selectFileBtnMouseClicked

    private void continueBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continueBtMouseClicked
        try{
            if (f == null) {
                throw new NullPointerException(); 
            }
            initPn.setVisible(false);
            DeteccionPn.setVisible(false);
            CorreccionPn.setVisible(false);
            MenuPn.setVisible(true);
        }catch(NullPointerException n){ //en caso de no haber seleccionado archivo
            JOptionPane.showMessageDialog(null, "No se ha especificado la ruta del archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_continueBtMouseClicked

    private void deteccionRbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deteccionRbFocusGained
        initPn.setVisible(false);
        DeteccionPn.setVisible(true);
        CorreccionPn.setVisible(false);
        MenuPn.setVisible(true);
    }//GEN-LAST:event_deteccionRbFocusGained

    private void correccionRbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correccionRbFocusGained
        initPn.setVisible(false);
        DeteccionPn.setVisible(false);
        CorreccionPn.setVisible(true);
        MenuPn.setVisible(true);
    }//GEN-LAST:event_correccionRbFocusGained

    private void recibirDetBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recibirDetBtMouseClicked
//        try{
//            
//        }catch(){
//        
//        }
        
    }//GEN-LAST:event_recibirDetBtMouseClicked

    private void enviarDetBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarDetBtMouseClicked
        try{
            generador = generadorTf.getText();
            Brain.AsignarPolinomioGenerador(generador);
            Identificador = 1;
            Brain.GetInfo(f, Identificador);
        }catch(StringIndexOutOfBoundsException n){ // en caso de que el TextField del generador quede vacío
            JOptionPane.showMessageDialog(null, "No se ha especificado el polinomio generador", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enviarDetBtMouseClicked

    private void selectFileDetBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFileDetBtMouseClicked
        try { //Manejo de excepcion para la recepción en la Detección de errores 
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File fi = chooser.getSelectedFile();
            nombreFile = fi.getName();
            Brain.AsignarNombreSalida(nombreFile);
        }catch(NullPointerException n){ //si no se selecciona archivo alguno
            JOptionPane.showMessageDialog(null, "No se ha especificado la ruta del archivo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_selectFileDetBtMouseClicked

    private void recibirCorBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recibirCorBtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_recibirCorBtMouseClicked

    private void selectFileCorBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectFileCorBtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selectFileCorBtMouseClicked

    private void enviarCorBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarCorBtMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarCorBtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPn;
    private javax.swing.JPanel CorreccionPn;
    private javax.swing.JPanel DeteccionPn;
    private javax.swing.JPanel HeadPn;
    private javax.swing.JPanel MenuPn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel continueBt;
    private javax.swing.JRadioButton correccionRb;
    private javax.swing.JRadioButton deteccionRb;
    private javax.swing.JLabel enviarCorBt;
    private javax.swing.JLabel enviarDetBt;
    private javax.swing.JPanel envioCorPn;
    private javax.swing.JPanel envioDetPn;
    private javax.swing.JTextField generadorTf;
    private javax.swing.JPanel initPn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel pathCorTx;
    private javax.swing.JLabel pathTx;
    private javax.swing.JPanel recepcionCorPn;
    private javax.swing.JPanel recepcionDetPn;
    private javax.swing.JLabel recibirCorBt;
    private javax.swing.JLabel recibirDetBt;
    private javax.swing.JLabel selectFileBtn;
    private javax.swing.JLabel selectFileCorBt;
    private javax.swing.JLabel selectFileDetBt;
    // End of variables declaration//GEN-END:variables
}
